#!/bin/bash
# OpenClaw Backup Script
# Backs up all custom configurations to GitHub

set -e

# Configuration
BACKUP_DIR="/home/ubuntu/.openclaw"
WORKSPACE_DIR="/home/ubuntu/.openclaw/workspace"
BACKUP_REPO_DIR="/tmp/openclaw-backup-repo"
BRANCH="main"
TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)

# Load credentials from config (not committed to git)
CONFIG_FILE="/home/ubuntu/.openclaw/workspace/skills/openclaw-backup/.backup-credentials"
if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
else
    echo "Error: Backup credentials not found at $CONFIG_FILE"
    exit 1
fi

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Clone or update repository
setup_repo() {
    log_info "Setting up backup repository..."
    
    rm -rf "$BACKUP_REPO_DIR"
    
    git clone "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git" "$BACKUP_REPO_DIR" 2>&1 | grep -v "Cloning into" || true
    
    cd "$BACKUP_REPO_DIR"
    git config user.email "sol@openclaw.local"
    git config user.name "Sol Backup"
    
    log_info "Repository ready"
}

# Create backup
create_backup() {
    log_info "Creating backup: $TIMESTAMP"
    
    cd "$BACKUP_REPO_DIR"
    
    # Clear previous backup
    rm -rf "$BACKUP_REPO_DIR"/*
    rm -rf "$BACKUP_REPO_DIR"/.backup-* 2>/dev/null || true
    
    # Create backup structure
    mkdir -p backup
    mkdir -p backup/skills
    mkdir -p backup/memory
    mkdir -p backup/workspace
    mkdir -p backup/config
    mkdir -p backup/cron
    
    # Backup skills
    log_info "Backing up skills..."
    if [ -d "$WORKSPACE_DIR/skills" ]; then
        cp -r "$WORKSPACE_DIR/skills"/* backup/skills/ 2>/dev/null || true
    fi
    
    # Backup memory
    log_info "Backing up memory..."
    if [ -d "$WORKSPACE_DIR/memory" ]; then
        cp -r "$WORKSPACE_DIR/memory"/* backup/memory/ 2>/dev/null || true
    fi
    
    # Backup workspace files
    log_info "Backing up workspace files..."
    cp "$WORKSPACE_DIR"/*.md backup/workspace/ 2>/dev/null || true
    cp "$WORKSPACE_DIR"/HEARTBEAT.md backup/workspace/ 2>/dev/null || true
    
    # Backup config
    log_info "Backing up configuration..."
    cp "$BACKUP_DIR/openclaw.json" backup/config/ 2>/dev/null || true
    
    # Backup agents config but exclude large session transcripts (already in memory)
    mkdir -p backup/config/agents
    if [ -d "$BACKUP_DIR/agents" ]; then
        cp "$BACKUP_DIR/agents/main/agent"/*.json backup/config/agents/ 2>/dev/null || true
        cp "$BACKUP_DIR/agents/main/sessions/sessions.json" backup/config/agents/ 2>/dev/null || true
        # Skip .jsonl files - they're already extracted to memory
    fi
    
    # Backup cron jobs
    log_info "Backing up cron job definitions..."
    if [ -d "$BACKUP_DIR/cron" ]; then
        cp -r "$BACKUP_DIR/cron"/* backup/cron/ 2>/dev/null || true
    fi
    
    # Create backup metadata
    cat > backup/BACKUP_INFO.md <<EOF
# OpenClaw Backup - $TIMESTAMP

**Created:** $(date)
**OpenClaw Version:** $(openclaw --version 2>/dev/null || echo "Unknown")
**Backup Size:** $(du -sh backup | cut -f1)

## What's Included

- Skills: $(find backup/skills -name "SKILL.md" 2>/dev/null | wc -l) skills
- Memory files: $(find backup/memory -name "*.md" 2>/dev/null | wc -l) files
- Configuration: openclaw.json, agents config
- Cron jobs: $(ls backup/cron/*.json 2>/dev/null | wc -l) jobs

## Restore Instructions

To restore this backup on a new machine:

1. Install OpenClaw (latest version)
2. Clone this repository
3. Run: ./scripts/restore.sh
4. Re-add API keys to ~/.openclaw/credentials/
5. Restart OpenClaw

## Backup Contents

- **skills/** - Custom skills (tavily-search, telegram-context, etc.)
- **memory/** - Complete memory system
- **workspace/** - SOUL.md, USER.md, AGENTS.md, etc.
- **config/** - Configuration files
- **cron/** - Cron job definitions

---
*Automatically generated by Sol Backup System*
EOF
    
    log_info "Backup created successfully"
}

# Commit and push
commit_backup() {
    log_info "Committing backup to Git..."
    
    cd "$BACKUP_REPO_DIR"
    
    # Add all files
    git add -A
    
    # Check if there are changes
    if git diff --staged --quiet; then
        log_info "No changes to commit"
        return 0
    fi
    
    # Commit
    git commit -m "Backup: $TIMESTAMP" -m "Automated backup of OpenClaw customizations"
    
    # Check if this is the WORKING MODEL backup
    if [ -f "$BACKUP_REPO_DIR/backup/WORKING_MODEL.md" ]; then
        log_info "WORKING MODEL backup - marking as PERMANENT"
        git tag -a "WORKING-MODEL-$(date +%Y-%m-%d)" -m "Permanent backup - never delete"
    fi
    
    # Push
    log_info "Pushing to GitHub..."
    if git push origin "$BRANCH" 2>&1; then
        log_info "Backup pushed to GitHub successfully!"
    else
        log_warn "Normal push failed, trying force push..."
        if git push -f origin "$BRANCH" 2>&1; then
            log_info "Force push successful!"
        else
            log_error "Both normal and force push failed"
            log_error "Please check repository branch protection rules"
            exit 1
        fi
    fi
}

# Main
main() {
    log_info "Starting OpenClaw backup..."
    
    setup_repo
    create_backup
    commit_backup
    
    log_info "Backup complete! View at: https://github.com/${GITHUB_REPO}"
    
    # Cleanup
    rm -rf "$BACKUP_REPO_DIR"
}

main "$@"
